"""initial_schema

Revision ID: 407617c5a0ae
Revises: 
Create Date: 2026-05-27 14:53:34.699749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '407617c5a0ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_code', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('upload_token', sa.String(length=255), nullable=True),
    sa.Column('project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('role_labels', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_access_token'), 'clients', ['access_token'], unique=True)
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=True)
    op.create_index(op.f('ix_clients_upload_token'), 'clients', ['upload_token'], unique=True)
    op.create_table('client_download_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('download_token', sa.String(length=255), nullable=False),
    sa.Column('blob_path', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_download_tokens_client_id'), 'client_download_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_download_tokens_download_token'), 'client_download_tokens', ['download_token'], unique=True)
    op.create_table('collateral_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=False),
    sa.Column('hu_moments', sa.ARRAY(sa.Double()), nullable=False),
    sa.Column('color_histogram', sa.ARRAY(sa.Double()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('array_length(color_histogram, 1) = 144', name='chk_color_histogram_length'),
    sa.CheckConstraint('array_length(hu_moments, 1) = 7', name='chk_hu_moments_length'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateral_signatures_client_id'), 'collateral_signatures', ['client_id'], unique=False)
    op.create_index(op.f('ix_collateral_signatures_phash'), 'collateral_signatures', ['phash'], unique=False)
    op.create_index(op.f('ix_collateral_signatures_task_id'), 'collateral_signatures', ['task_id'], unique=False)
    op.create_table('upload_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('Uploaded', 'Processing', 'Transcribing', 'In Review', 'Delivered', 'Error', 'Failed', name='job_status_enum'), nullable=False),
    sa.Column('category', sa.Enum('audio', 'jewelry', 'housing', 'business', 'form', 'clickstream', 'transcript', 'auto', name='job_category_enum'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_batch', sa.Boolean(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('parent_zip', sa.String(length=255), nullable=True),
    sa.Column('sub_blob_name', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('labelstudio_error', sa.String(), nullable=True),
    sa.Column('predictions_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_logs_batch_id'), 'upload_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_upload_logs_client_id'), 'upload_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_upload_logs_uploaded_at'), 'upload_logs', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###

    # Fix 2: PL/pgSQL updated_at trigger logic
    op.execute("""
      CREATE OR REPLACE FUNCTION update_modified_column()
      RETURNS TRIGGER AS $$
      BEGIN
          NEW.updated_at = CURRENT_TIMESTAMP;
          RETURN NEW;
      END;
      $$ language 'plpgsql';
    """)

    op.execute("""
      CREATE TRIGGER trigger_update_upload_logs_timestamp
      BEFORE UPDATE ON upload_logs
      FOR EACH ROW
      EXECUTE FUNCTION update_modified_column();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_logs_uploaded_at'), table_name='upload_logs')
    op.drop_index(op.f('ix_upload_logs_client_id'), table_name='upload_logs')
    op.drop_index(op.f('ix_upload_logs_batch_id'), table_name='upload_logs')
    
    # Fix 2 Cleanup: Drop trigger and function before dropping the upload_logs table
    op.execute("DROP TRIGGER IF EXISTS trigger_update_upload_logs_timestamp ON upload_logs;")
    op.execute("DROP FUNCTION IF EXISTS update_modified_column;")
    
    op.drop_table('upload_logs')
    op.drop_index(op.f('ix_collateral_signatures_task_id'), table_name='collateral_signatures')
    op.drop_index(op.f('ix_collateral_signatures_phash'), table_name='collateral_signatures')
    op.drop_index(op.f('ix_collateral_signatures_client_id'), table_name='collateral_signatures')
    op.drop_table('collateral_signatures')
    op.drop_index(op.f('ix_client_download_tokens_download_token'), table_name='client_download_tokens')
    op.drop_index(op.f('ix_client_download_tokens_client_id'), table_name='client_download_tokens')
    op.drop_table('client_download_tokens')
    op.drop_index(op.f('ix_clients_upload_token'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_index(op.f('ix_clients_access_token'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
